name: SE_cbook_4096_1_128_lr_1m5_1m5_github
###########################################################
#                   DATA SETTING                          #
###########################################################
# user defined data path
vctk_Clean_path: '/vctk_data/clean_testset_wav_16k/'
DNS1_test: '/DNS1_test'
DNS3_test: '/DNS3_test'

sampling_rate: 16000
data:
    path: ""
    subset:
        clean_train: "./VCTK_clean_train.csv"
        clean_valid: "./VCTK_clean_test.csv" # not actually used
###########################################################
#                   MODEL SETTING                         #
###########################################################
task: Speech_Enhancement  # Speech_Enhancement or Quality_Estimation
train_mode: autoencoder
cos_loss: False
input_transform: log1p

adv_min_epsilon: 0.03
adv_max_epsilon: 0.55

VQVAE_params:
    codebook_size: 4096 
    codebook_num: 1
    codebook_dim: 128
    orthogonal_reg_weight: 0
    use_cosine_sim: False
    ema_update: True
    learnable_codebook: False
    stochastic_sample_codes: False
    sample_codebook_temp: 6
    straight_through: False
    reinmax: False
    kmeans_init: True
    threshold_ema_dead_code: -1000

###########################################################
#                  LOSS WEIGHT SETTING                    #
###########################################################
lambda_vq_loss: 3.0      # Loss weight of vector quantize loss.
lambda_ce_loss: 1.0      # Loss weight of cross-entropy loss.
lambda_stft_loss: 45.0   # Loss weight of stft loss.
      
###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 64              # Batch size.
batch_length: 48000         # Length of each audio in batch.
pin_memory: true            # Whether to pin memory in Pytorch DataLoader.
num_workers: 6              # Number of workers in Pytorch DataLoader.

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
VQVAE_optimizer_type: Adam
VQVAE_optimizer_params:
    lr: 1.0e-5
    betas: [0.5, 0.9]
    weight_decay: 0.0
VQVAE_scheduler_type: StepLR
VQVAE_scheduler_params:
    step_size: 200000      # Generator's scheduler step size.
    gamma: 1.0
VQVAE_grad_norm: -1

VQVAE_AT_optimizer_params:
    lr: 1.0e-5
    betas: [0.5, 0.9]
    weight_decay: 0.0

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
start_steps:                       # Number of steps to start training
    VQVAE: 0
AT_training_start_steps: 400000
train_max_steps: 500000             # Number of training steps.
save_interval_steps: 100000         # Interval steps to save checkpoint.
eval_interval_steps: 20000          # Interval steps to evaluate the network.
log_interval_steps: 20000           # Interval steps to record the training log.
